project:
  type: website
  output-dir: docs

website:
  title: "DATA334blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/BrodyPinto
      - icon: linkedin
        href: https://linkedin.com/in/brodypinto/
format:
  html:
    theme: minty
    css: styles.css



