---
title: "Blog Post #2: Big Tech Stock Prices"
author: "Brody Pinto"
date: "2024-02-19"
categories: [code, analysis]
---

```{r}
#| warning: false
library(tidyverse)
library(tidytuesdayR)
library(lubridate)

theme_set(theme_minimal())

tuesdata <- tidytuesdayR::tt_load('2023-02-07')
tuesdata <- tidytuesdayR::tt_load(2023, week = 6)

big_tech_stock_prices <- tuesdata$big_tech_stock_prices
big_tech_companies <- tuesdata$big_tech_companies
```

```{r}
stocks <- big_tech_stock_prices |> 
  left_join(big_tech_companies, by = c("stock_symbol" = "stock_symbol")) |>
  relocate(company) |>
  mutate(weekday = weekdays(date),
         month = month(date, label = TRUE),
         year = year(date))

head(stocks)
```

```{r}
## yearly volume
#| warning: false
yearly_volume = stocks |>
  group_by(company, year) |>
  summarise(mean_price = mean(volume),
            sd_volume = sd(volume),
            sample_size = n()) |>
  mutate(se = sd_volume / sqrt(sample_size), ## se for means
         lower = mean_volume - se,
         upper = mean_volume + se)
head(yearly_volume)

ggplot(data = yearly_volume, aes(x = year, y = mean_volume, col = company)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), col = "black", width = 0.25) +
  geom_line()

## yearly price
#| warning: false
yearly_price = stocks |>
  group_by(company, year) |>
  summarise(mean_price = mean(high),
            sd_price = sd(high),
            sample_size = n()) |>
  mutate(se = sd_price / sqrt(sample_size), ## se for means
         lower = mean_price - se,
         upper = mean_price + se)
yearly_price

ggplot(data = yearly_price, aes(x = year, y = mean_price, col = company)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), col = "black", width = 0.25) +
  geom_line()

## find the five most popular stocks traded in most collectively most recent year - 2022
top_5_summary = yearly_volume |> filter(year == 2022) |>
  arrange(desc(mean_volume)) |>
  filter(company == "Apple Inc." || company == "Tesla, Inc." || company == "Amazon.com, Inc." || company == "NVIDIA Corporation" || company == "Intel Corporation") |>
  mutate(company = fct_reorder(company, mean_volume))

top_5_summary

ggplot(data = top_5_summary, aes(x = company, y = mean_volume)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), col = "lightblue", width = 0.1) +
  geom_point(col = "lightblue3")
```










